# Generated by Django 3.1.7 on 2021-03-11 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evraka', '0002_auto_20210311_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='navigationrecord',
            name='vehicle',
            field=models.CharField(max_length=60, null=True, verbose_name='Araç'),
        ),
    ]
